version: '3.3'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80

networks:
     default:
       external:
         name: webapp
volumes:
  mysql_data: {}