version: '3'

services:
    prometheus:
        image: prom/prometheus:v2.40.1
        container_name: ${COMPOSE_PROJECT_NAME}_prometheus
        volumes:
        - ./grafana_stack/prometheus:/etc/prometheus
        - prometheus_data:/prometheus
        command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/etc/prometheus/console_libraries'
        - '--web.console.templates=/etc/prometheus/consoles'
        - '--storage.tsdb.retention.time=200h'
        - '--web.enable-lifecycle'
        restart: unless-stopped
        expose:
        - 9090
        networks:
            public_net:
                ipv4_address: ${PROMETHEUS_IP}
        labels:
            org.label-schema.group: "monitoring"

    alertmanager:
        image: prom/alertmanager:v0.24.0
        container_name: ${COMPOSE_PROJECT_NAME}_alertmanager
        volumes:
        - ./grafana_stack/alertmanager:/etc/alertmanager
        command:
        - '--config.file=/etc/alertmanager/config.yml'
        - '--storage.path=/alertmanager'
        restart: unless-stopped
        expose:
        - 9093
        networks:
            public_net:
                ipv4_address: ${ALERTMGR_IP}
        labels:
            .label-schema.group: "monitoring"

    nodeexporter:
        image: prom/node-exporter:v1.4.0
        container_name: ${COMPOSE_PROJECT_NAME}_nodeexporter
        volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro
        command:
        - '--path.procfs=/host/proc'
        - '--path.rootfs=/rootfs'
        - '--path.sysfs=/host/sys'
        - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
        restart: unless-stopped
        expose:
        - 9100
        networks:
            public_net:
                ipv4_address: ${NODEEXPORTER_IP}
        labels:
            org.label-schema.group: "monitoring"

    grafana:
        image: grafana/grafana:9.2.4
        container_name: ${COMPOSE_PROJECT_NAME}_grafana
        volumes:
        - grafana_data:/var/lib/grafana
        - ./grafana_stack/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
        - ./grafana_stack/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
        environment:
        - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
        - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
        - GF_USERS_ALLOW_SIGN_UP=false
        restart: unless-stopped
        expose:
        - 3000
        networks:
            public_net:
                ipv4_address: ${GRAFANA_IP}
        labels:
            org.label-schema.group: "monitoring"

    pushgateway:
        image: prom/pushgateway:v1.4.3
        container_name: ${COMPOSE_PROJECT_NAME}_pushgateway
        restart: unless-stopped
        expose:
        - 9091
        networks:
            public_net:
                ipv4_address: ${PUSHGATEWAY_IP}
        labels:
            org.label-schema.group: "monitoring"

    caddy:
        image: caddy:2.6.2
        container_name: ${COMPOSE_PROJECT_NAME}_caddy
        ports:
        - "3000:3000"
        - "9090:9090"
        - "9093:9093"
        - "9091:9091"
        volumes:
        - ./grafana_stack/caddy:/etc/caddy
        environment:
        - ADMIN_USER=${ADMIN_USER:-admin}
        - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
        - ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH:-$2a$14$1l.IozJx7xQRVmlkEQ32OeEEfP5mRxTpbDTCTcXRqn19gXD8YK1pO}
        restart: unless-stopped
        networks:
            public_net:
                ipv4_address: ${CADDY_IP}
        labels:
            org.label-schema.group: "monitoring"

    mysql:
        container_name: ${COMPOSE_PROJECT_NAME}_mysql
        build: ./docker_mysql
        volumes:
            - mysql_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        networks:
            public_net:
                ipv4_address: ${MYSQL_IP}

    phpmyadmin:
        container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
        build: ./docker_phpmyadmin
        environment:
            PMA_HOST: ${MYSQL_IP}
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8183:80
        networks:
            public_net:
                ipv4_address: ${PHPMYADMIN_IP}

    wordpress_img_1:
        container_name: ${COMPOSE_PROJECT_NAME}_wordpress_con_1
        build: ./docker_wordpress
        expose:
            - ${WORDPRESS_EXPOSED_PORT}
        environment:
            WORDPRESS_DB_HOST: mysql:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
        volumes:
            - ./wordpress_data/themes:/var/www/html/wp-content/themes
            - ./wordpress_data/plugins:/var/www/html/wp-content/plugins
            - ./wordpress_data/uploads:/var/www/html/wp-content/uploads
        networks:
            public_net:
                ipv4_address: ${WORDPRESS_1_IP}

    wordpress_img_2:
        container_name: ${COMPOSE_PROJECT_NAME}_wordpress_con_2
        build: ./docker_wordpress
        expose:
            - ${WORDPRESS_EXPOSED_PORT}
        environment:
            WORDPRESS_DB_HOST: mysql:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
        volumes:
            - ./wordpress_data/themes:/var/www/html/wp-content/themes
            - ./wordpress_data/plugins:/var/www/html/wp-content/plugins
            - ./wordpress_data/uploads:/var/www/html/wp-content/uploads
        networks:
            public_net:
                ipv4_address: ${WORDPRESS_2_IP}

    wordpress_img_3:
        container_name: ${COMPOSE_PROJECT_NAME}_wordpress_con_3
        build: ./docker_wordpress
        expose:
            - ${WORDPRESS_EXPOSED_PORT}
        environment:
            WORDPRESS_DB_HOST: mysql:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
        volumes:
            - ./wordpress_data/themes:/var/www/html/wp-content/themes
            - ./wordpress_data/plugins:/var/www/html/wp-content/plugins
            - ./wordpress_data/uploads:/var/www/html/wp-content/uploads
        networks:
            public_net:
                ipv4_address: ${WORDPRESS_3_IP}

    haproxy_img:
        build: ./docker_haproxy
        ports:
            - 8090:80
        expose:
            - 8090
        networks:
            public_net:
                ipv4_address: ${HA_PROXY_IP}
        environment:
            - WORDPRESS_1_IP=${WORDPRESS_1_IP}
            - WORDPRESS_2_IP=${WORDPRESS_2_IP}
            - WORDPRESS_3_IP=${WORDPRESS_3_IP}
            - WORDPRESS_EXPOSED_PORT=${WORDPRESS_EXPOSED_PORT}



networks:
    public_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}

volumes:
    mysql_data: {}
    prometheus_data: {}
    grafana_data: {}